
GET http://127.0.0.1:5000/api/greet/Ronal

###
POST http://127.0.0.1:5000/api/data HTTP/1.2
Content-Type: application/json 

{ 
    "key": "value"
}

###

PUT http://127.0.0.1:5000/api/data/1 HTTP/1.1
Content-Type: application/json 

{
    "new_key": "new_value"
}

###

curl -X DELETE http://127.0.0.1:5000/api/data/1

